"""生成 `ferro-io/src/readers/spacegroups.dat`：spglib 的 530 条 Hall 设置及其全部对称操作。

CIF 只写空间群符号（H-M / Hall / IT 号）而不列对称操作时，CIF reader 靠这张表展开。
数据取自 spglib（BSD-3-Clause）而非 ASE 的 `spacegroup.dat`（LGPL），因为表要经
`include_str!` 编进 MIT 许可的二进制。

运行（需要 spglib，deepmd 环境里有）：

    ~/.miniforge3/envs/deepmd/bin/python scripts/gen_spacegroups.py

输出格式（`#` 开头为注释）：
    表头行（tab 分隔）：hall 号 · IT 号 · choice（空写 `-`）· Hall 符号 ·
        本设置的 H-M 符号 · 短符号 · 全符号 · 操作数
    随后每个操作一行 12 个整数：旋转矩阵按行 9 个 · 平移 3 个（单位 1/24）
"""

from pathlib import Path

import numpy as np
import spglib

OUT = Path(__file__).resolve().parent.parent / "ferro-io/src/readers/spacegroups.dat"

LICENSE = """\
Copyright (c) 2024, Spglib team

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

* Redistributions of source code must retain the above copyright
  notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above copyright
  notice, this list of conditions and the following disclaimer in the
  documentation and/or other materials provided with the distribution.
* Neither the name of the <organization> nor the
  names of its contributors may be used to endorse or promote products
  derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT
HOLDER> BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""


def main():
    lines = [
        f"# Generated by scripts/gen_spacegroups.py from spglib {spglib.__version__}.",
        "# Do not edit by hand. Data derived from spglib, used under the following license:",
        "#",
        *[f"# {l}".rstrip() for l in LICENSE.splitlines()],
        "#",
        "# header: hall<TAB>number<TAB>choice<TAB>hall_symbol<TAB>hm_setting<TAB>hm_short<TAB>hm_full<TAB>n_ops",
        "# op:     r11 r12 r13 r21 r22 r23 r31 r32 r33 t1 t2 t3   (t in units of 1/24)",
    ]
    n_ops_total = 0
    for hall in range(1, 531):
        t = spglib.get_spacegroup_type(hall)
        sym = spglib.get_symmetry_from_database(hall)
        rots, trans = sym["rotations"], sym["translations"]
        # `international` 形如 'P 2_1/c = P 1 2_1/n 1'，等号后才是本设置专用的符号
        hm_setting = t.international.split("=")[-1].strip()
        # spglib 2.7 的 Hall 331（68 号 bca 轴序原点 2）写成 'B b c b'，同轴序原点 1（330）
        # 与 ITA 都是 'B b e b'。不改则 'B b e b :2' 只剩 a-cb 一个候选，被静默选中
        if hall == 331:
            assert hm_setting in ("B b c b", "B b e b"), hm_setting
            hm_setting = "B b e b"
        fields = [hall, t.number, t.choice or "-", t.hall_symbol, hm_setting,
                  t.international_short, t.international_full, len(rots)]
        assert all("\t" not in str(f) for f in fields)
        lines.append("\t".join(str(f) for f in fields))
        for r, tr in zip(rots, trans):
            t24 = np.mod(tr, 1.0) * 24
            t24_int = np.rint(t24).astype(int) % 24
            assert np.allclose(t24, np.rint(t24), atol=1e-8), (hall, tr)
            lines.append(" ".join(str(int(v)) for v in [*r.ravel(), *t24_int]))
        n_ops_total += len(rots)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}: 530 settings, {n_ops_total} operations")


if __name__ == "__main__":
    main()
